# Generated by Django 5.1.4 on 2024-12-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('experience', 'Experience'), ('guidance', 'Guidance'), ('roadmaps', 'Roadmaps'), ('tools_resources', 'Tools & Resources'), ('best_practices', 'Best Practices'), ('career_development', 'Career Development'), ('project_showcase', 'Project Showcase'), ('learning_challenges', 'Learning Challenges'), ('tech_news_trends', 'Tech News & Trends'), ('community_stories', 'Community Stories')], default='guidance', max_length=50),
        ),
    ]
